name: Release Drafter

on:
  push:
    branches:
      - main

# Comment out the 2 lines if the permissions for the GITHUB_TOKEN is read and write and you get an workflow runtime error
permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
           config-name: release-drafter.yml
           disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
